language: go

go:
  - 1.10.x

go_import_path: github.com/gemalto/gokube

env:
  global:
    - ARTIFACT_NAME=gokube-windows-amd64.exe

before_install:

install:
- GOOS=windows GOARCH=amd64 go get -t -v ./...

script:
- cd cmd/gokube
- GOOS=windows GOARCH=amd64 go build -o bin/$ARTIFACT_NAME

deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: bin/$ARTIFACT_NAME
  skip_cleanup: true # Important, otherwise the build output would be purged.
  on:
    tags: true # The deployment happens only if the commit has a tag.