name: Release on github
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/src/github.com/gemalto/gokube
      - name: Make release
        run: |
          cd ${{ github.workspace }}/src/github.com/gemalto/gokube
          GOOS=windows GOARCH=amd64 go get -t -v ./...
          cd cmd/gokube
          GOOS=windows GOARCH=amd64 go build -o ${{ github.workspace }}/bin/gokube-windows-amd64.exe
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: ${{ github.workspace }}/bin/gokube*
